import type { Locale } from '@jea/app'

const copy = {
  en: {
    subjects: 'Subjects',
    noSubjects: 'No subjects yet',
    defaultBadge: 'default',
    conversation: 'Subject conversation',
    conversationHint: 'Messages use the Channel classifier, presence, and speech pipeline. This is not a direct model chat.',
    emptyMessages: 'No messages yet.',
    draftPlaceholder: 'Send a governed message through the Subject Channel…',
    send: 'Send',
    sending: 'Sending…',
    retry: 'Retry',
    stopWaiting: 'Stop waiting',
    waiting: 'Waiting for the Channel pipeline to persist an assistant reply…',
    pending: 'Message is queued on the governed Channel path.',
    failed: 'Send failed',
    enableDesktop: 'Enable desktop Channel',
    enableDesktopHint: 'This Subject does not enable channels.desktop. Enabling writes the minimum safe desktop and presence configuration. Existing Subjects are never changed unless you confirm.',
    startService: 'Start channel service',
    startingService: 'Starting channel service…',
    serviceStartFailed: 'Unable to start the channel service.',
    startServiceHint: 'The channel daemon is stopped or unhealthy. Start or attach it to continue.',
    serviceStartUnavailable: 'This host cannot start the channel service automatically.',
    modelMock: 'Running in mock mode. A live model key is not required.',
    modelUnset: 'No model is configured.',
    webRejected: 'This host rejected the conversation command. The message was not sent.',
    you: 'You',
    assistant: 'JEA',
    loading: 'Loading conversation…',
    loadFailed: 'Unable to load conversation state.',
    sendFailed: 'Unable to send the desktop message.',
    enableFailed: 'Unable to enable desktop Channel.',
    serviceOnline: 'Channel service ready',
    serviceOffline: 'Channel service offline',
    serviceDegraded: 'Channel service degraded',
    serviceStarting: 'Channel service starting',
    serviceStale: 'Live status is stale'
  },
  zh: {
    subjects: '主体',
    noSubjects: '还没有主体',
    defaultBadge: '默认',
    conversation: '主体对话',
    conversationHint: '消息会走 Channel 分类、在场与话术管线，不是直接的模型聊天。',
    emptyMessages: '还没有消息。',
    draftPlaceholder: '通过主体 Channel 发送一条受治理的消息…',
    send: '发送',
    sending: '发送中…',
    retry: '重试',
    stopWaiting: '停止等待',
    waiting: '正在等待 Channel 管线写入助手回复…',
    pending: '消息已进入受治理的 Channel 路径。',
    failed: '发送失败',
    enableDesktop: '启用桌面 Channel',
    enableDesktopHint: '该主体尚未启用 channels.desktop。启用只会写入最小安全的桌面与在场配置；未经确认不会改动现有主体。',
    startService: '启动 Channel 服务',
    startingService: '正在启动 Channel 服务…',
    serviceStartFailed: '无法启动 Channel 服务。',
    startServiceHint: 'Channel daemon 已停止或不健康。请启动或接入后再继续。',
    serviceStartUnavailable: '当前宿主无法自动启动 Channel 服务。',
    modelMock: '当前为 mock 模式，不需要真实模型密钥。',
    modelUnset: '尚未配置模型。',
    webRejected: '当前宿主拒绝了该对话命令，消息没有发出。',
    you: '你',
    assistant: 'JEA',
    loading: '正在加载对话…',
    loadFailed: '无法加载对话状态。',
    sendFailed: '无法发送桌面消息。',
    enableFailed: '无法启用桌面 Channel。',
    serviceOnline: 'Channel 服务就绪',
    serviceOffline: 'Channel 服务离线',
    serviceDegraded: 'Channel 服务降级',
    serviceStarting: 'Channel 服务启动中',
    serviceStale: '实时状态已过期'
  }
} as const

export type ConversationCopyKey = keyof typeof copy.en

export function conversationText(locale: Locale, key: ConversationCopyKey): string {
  return copy[locale][key]
}
