export { createConversationFeature, CONVERSATION_FEATURE_ID } from './feature'
export { createDesktopProjectionWatchPort, createRendererJeaClient } from './host-client'
export type { ProjectionWatchPort } from './watch'
export { ConversationWorkspaceModel } from './model'
export { createConversationHarness, fixtureSubjectReadiness, TEST_CONVERSATION_SUBJECT } from './harness'
export { resolveDraftAttempt, type DraftAttempt } from './draft'
export { MAX_CHANNEL_RECORDS, mergeRecords, type WorkspaceMessage } from './history'
export { deriveInlineCards, cardKindFromMessage } from './cards'
export { classifyClientError } from './errors'
export { deriveConversationRecovery, conversationCanCompose } from './recovery'
